#!/bin/sh
set -e
set -x

echo "[bff-products] Corriendo lint..."
npm run lint || exit 1
echo "[bff-products] Corriendo prettier-check..."
npm run prettier-check || exit 1
# echo "[bff-products] Corriendo tests..."
# npm test || exit 1
