services:
  int-products-ms:
    build:
      context: ./int-products-ms
    image: int-products-ms:latest
    container_name: int-products-ms
    ports:
      - "3000:3000"
    volumes:
      - ./int-products-ms:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev
    networks:
      - ms-net

  int-category-ms:
    build:
      context: ./int-category-ms
    image: int-category-ms:latest
    container_name: int-category-ms
    ports:
      - "3001:3001"
    volumes:
      - ./int-category-ms:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev
    networks:
      - ms-net

  fcd-products:
    build:
      context: ./fcd-products
    image: fcd-products:latest
    container_name: fcd-products
    ports:
      - "3002:3002"
    volumes:
      - ./fcd-products:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev
    networks:
      - ms-net
  
  bff-products:
    build:
      context: ./bff-products
    image: bff-products:latest
    container_name: bff-products
    ports:
      - "3003:3003"
    volumes:
      - ./bff-products:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev
    networks:
      - ms-net

networks:
  ms-net:
    driver: bridge